export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  category: string;
  description: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Durateston Lander Gold",
    price: 200,
    image: "/images/durateston.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Alpha.",
  },
  {
    id: 2,
    name: "Cipionato de Testo Lander Gold",
    price: 200,
    image: "/images/cipionato.png",
    category: "Linha Gold",
    description: "Descrição completa do Produto Beta.",
  },
  {
    id: 3,
    name: "Enantato de Testo Lander Gold",
    price: 200,
    image: "/images/enantato.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 4,
    name: "Boldenona Lander Gold",
    price: 200,
    image: "/images/boldenona.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Alpha.",
  },
  {
    id: 5,
    name: "Deca lander Gold",
    price: 200,
    image: "/images/decaland.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Beta.",
  },
  {
    id: 6,
    name: "NPP Lander Gold",
    price: 200,
    image: "/images/npp.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 7,
    name: "Masteron Lander Gold",
    price: 200,
    image: "/images/masteron.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 8,
    name: "Trembolona Acetado Lander Gold",
    price: 230,
    image: "/images/acetato-trembo.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 9,
    name: "Trembolona Enantato Lander Gold",
    price: 200,
    image: "/images/enantato-trembo.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 10,
    name: "Primobolan Enantato Lander Gold",
    price: 400,
    image: "/images/primobolan.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 11,
    name: "HCG 5MIL Ui",
    price: 230,
    image: "/images/hcg.jpg",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 12,
    name: "Dura Lander 1 ml - Pedido min 5",
    price: 35,
    image: "/images/duratesto-1ml.jpg",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 13,
    name: "Clembuterol Lander Gold",
    price: 150,
    image: "/images/clembuterol.png",
    category: "Linha Gold",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 14,
    name: "Hemogenin Lander",
    price: 110,
    image: "/images/hemogenin-20cmp.jpg",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 15,
    name: "Diana Lander",
    price: 110,
    image: "/images/diana-100cmp.png",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 16,
    name: "Stano Lander",
    price: 140,
    image: "/images/stano-15ml.png",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 17,
    name: "Stanozoland Lander",
    price: 170,
    image: "/images/stano-100cmp.png",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 18,
    name: "Oxandrolona Lander",
    price: 250,
    image: "/images/oxandrolona-50cmp.jpg",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 19,
    name: "Oxandrolona Lander",
    price: 250,
    image: "/images/oxandrolona-100cmp.jpg",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 20,
    name: "Proviron Lander",
    price: 150,
    image: "/images/proviron.jpg",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 21,
    name: "Tirzepatida Combo/15mg",
    price: 1600,
    image: "/images/tirzepartidacombo.jpeg",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
  {
    id: 22,
    name: "Tirzepatida Unidade",
    price: 400,
    image: "/images/tirzepatida.jpeg",
    category: "Linha Premium",
    description: "Descrição completa do Produto Gama.",
  },
];
